# ==============================================================================
# Word List 03
# ==============================================================================


leak:   
  title: leak
  text: |
    __leak__ [liːk] n. 漏洞；泄露 

    __leak__ v. （使）漏，（使）渗出

literature:   
  title: literature
  text: __literature__ [ˈlɪtrətʃə(r)] n. 文学（作品）；文献

suffer:   
  title: suffer
  text: __suffer__ [ˈsʌfə(r)] v. 遭受，忍受；忍耐；容许；患病；受损失

impede:   
  title: impede
  text: __impede__ [ɪmˈpiːd] vt. 阻碍，妨碍

spring:   
  title: spring
  text: |
    __spring__ [sprɪŋ] n. 春天，春季；弹簧，发条；弹性，弹力；（源）泉；跳跃  

    __spring__ v. 跳跃；涌现，突然出现；突然提出（或说出）

biological:   
  title: biological
  text: __biological__ [ˏbaɪəˈlɔdʒɪkl] a. 生物的；生物学的，有关生物学的

deduce:   
  title: deduce
  text: __deduce__ [dɪˈdjuːs] v. 演绎，推断

doctorate:   
  title: doctorate
  text: __doctorate__ ['dɒktərɪt] n. 博士学位

absolute:   
  title: absolute
  text: __absolute__ [ˈæbsəluːt] a. 完全的，绝对的，纯粹的

theoretical:   
  title: theoretical
  text: __theoretical__ [ˏθɪəˈretɪkl] a. 理论（上）的

internship:   
  title: internship
  text: __internship__ ['ɪntɜːnʃɪp] n. 实习身份；实习医师

slender:   
  title: slender
  text: __slender__ [ˈslendə(r)] a. 修长的，细长的，苗条的；微小的，微薄的

respondent:   
  title: respondent
  text: __respondent__ [rɪˈspɔndənt] n. 回答者，响应者；调查对象；被告

surroundings:   
  title: surroundings
  text: __surroundings__ [səˈraʊndɪŋz] n. 周围的事物，环境

couple:   
  title: couple
  text: |
    __couple__ [ˈkʌpl] n. （一）对，（一）双；夫妇；  

    __couple__ v. 连接，联合，结合；结婚

voluntary:   
  title: voluntary
  text: __voluntary__ [ˈvɔləntrɪ] a. 自愿的，志愿的

submarine:   
  title: submarine
  text: |
    __submarine__ [ˏsʌbməˈriːn; ˈsʌbməriːn] n. 潜水艇  

    __submarine__ a. 水底的，海底的

commercial:   
  title: commercial
  text: |
    __commercial__ [kəˈmɜːʃl] a. 商业的，商品化的，贸易的  

    __commercial__ n. 商业广告

notion:   
  title: notion
  text: __notion__ [ˈnəuʃn] n. 概念，观念；想法

lavatory:   
  title: lavatory
  text: __lavatory__ [ˈlævətrɪ] n. 盥洗室，厕所

tablet:   
  title: tablet
  text: __tablet__ [ˈtæblɪt] n. 药片

actual:   
  title: actual
  text: __actual__ [ˈæktʃuəl] a. 实际的；真实的

fold:   
  title: fold
  text: |
    __fold__ [fəuld] v. 折叠  

    __fold__ n. 皱；折

instrument:   
  title: instrument
  text: __instrument__ [ˋɪnstrəmənt] n. 仪器；手段；工具；乐器

simplify:   
  title: simplify
  text: __simplify__ [ˈsɪmplɪfaɪ] vt. 使简化

compulsory:   
  title: compulsory
  text: __compulsory__ [kəmˈpʌlsərɪ] a. 义务的；必须做的；强制性的；（课程）必修的

irritation:   
  title: irritation
  text: __irritation__ [‚ɪrɪ'teɪʃn] n. 激怒，恼怒；刺激物，恼人的事

expense:   
  title: expense
  text: __expense__ [ɪkˈspens] n. 花费，开支；消费，消耗；代价，损失

muddle:   
  title: muddle
  text: |
    __muddle__ [ˈmʌdl] n. 一团糟，凌乱，混乱；（头脑）糊涂，困惑  

    __muddle__ vt. 将……弄成一团糟；使困惑，使糊涂；混淆

originate:   
  title: originate
  text: __originate__ [əˈrɪdʒɪneɪt] v. 起源，发生；首创，创造

induce:   
  title: induce
  text: __induce__ [ɪnˈdjuːs] vt. 引诱，劝使；引起，导致；感应

exchange:   
  title: exchange
  text: |
    __exchange__ [ɪksˈtʃeɪndʒ] v. 交换，调换；交易；兑换；交流；谈话，争论  

    __exchange__ n. 交换，调换；交易（所）；兑换（率）；交流

disharmony:   
  title: disharmony
  text: __disharmony__ [dɪsˈhɑːmənɪ] n. 不一致；不和谐

cosset:   
  title: cosset
  text: |
    __cosset__ [ˈkɔsɪt] vt. 宠爱，溺爱 

    __cosset__ n. 宠儿

unique:   
  title: unique
  text: __unique__ [juːˈniːk] a. 唯一的，独一无二的；极不寻常的，极好的

crossword:   
  title: crossword
  text: __crossword__ [ˈkrɔswɜːd] n. 纵横填字游戏

atomic:   
  title: atomic
  text: __atomic__ [əˈtɔmɪk] a. 原子（能）的

disagree:   
  title: disagree
  text: __disagree__ [ˏdɪsəˈgriː] v. 不同意；不一致

check-up:   
  title: check-up
  text: __check-up__ ['tʃekʌp] n. 检查

silt:   
  title: silt
  text: |
    __silt__ [sɪlt] n. 淤泥  

    __silt__ v. （用淤泥）阻塞

inclusive:   
  title: inclusive
  text: __inclusive__ [ɪnˈkluːsɪv] a. 包括一切费用在内的；所有数目（或首尾日期）包括在内的；包容广阔的

reservation:   
  title: reservation
  text: __reservation__ [ˏrezəˈveɪʃn] n. 保留意见，存疑；预定，预订

transcript:   
  title: transcript
  text: __transcript__ ['trænskrɪpt] n. 抄本，副本；文字记录

include:   
  title: include
  text: __include__ [ɪnˈkluːd] v. 包括，包含；计入

reasonable:   
  title: reasonable
  text: __reasonable__ [ˈriːznəbl] a. 合理的，有道理的；通情达理的；适度的

abode:   
  title: abode
  text: __abode__ [əˈbəud] n. 房屋，家，住所

gadget:   
  title: gadget
  text: __gadget__ [ˈgædʒɪt] n. 小巧的器械，精巧的装置；小玩意

emergency:   
  title: emergency
  text: __emergency__ [ɪˈmɜːdʒənsɪ] n. 紧急情况，突发事件

legacy:   
  title: legacy
  text: __legacy__ [ˈlegəsɪ] n. 遗产，遗赠

leisure:   
  title: leisure
  text: __leisure__ [ˈleʒə(r)] n. 空闲时间；悠闲

overlap:   
  title: overlap
  text: __overlap__ [ˏəuvəˈlæp] v. （使）部分重叠，交叠

counterpart:   
  title: counterpart
  text: __counterpart__ [ˈkauntəpɑːt] n. 与对方地位相当的人；配对物；副本

tune:   
  title: tune
  text: |
    __tune__ [tjuːn] vt. 调音；调节，调整  

    __tune__ n. 调子；和谐

strike:   
  title: strike
  text: |
    __strike__ [straɪk] v. 打；折磨  

    __strike__ n. 罢工

ambiguous:   
  title: ambiguous
  text: __ambiguous__ [æmˈbɪgjuəs] a. 含糊其辞的； 不明确的，模棱两可的

represent:   
  title: represent
  text: __represent__ [ˏreprɪˈzent] vt. 代表；表示；表现

vanish:   
  title: vanish
  text: __vanish__ [ˈvænɪʃ] vi. 突然消失； 不复存在，消逝

mechanism:   
  title: mechanism
  text: __mechanism__ [ˈmekənɪzəm] n. 机械装置；机制，机理；办法

dispute:   
  title: dispute
  text: |
    __dispute__ [dɪˈspjuːt] n. 争论，争端，争吵  

    __dispute__ v. 对……表示异议；争论，争吵

furniture:   
  title: furniture
  text: __furniture__ [ˈfɜːnɪtʃə(r)] n. 家具

standard:   
  title: standard
  text: |
    __standard__ [ˈstændəd] n. 标准  

    __standard__ a. 标准的

typical:   
  title: typical
  text: __typical__ [ˈtɪpɪkl] a. 典型的

strengthen:   
  title: strengthen
  text: __strengthen__ ['strŋθn] vt. 加强，巩固

workaholic:   
  title: workaholic
  text: __workaholic__ [ˏwɜːkəˈhɔlɪk] n. 工作狂

unaware:   
  title: unaware
  text: __unaware__ [ˏʌnəˈweə(r)] a. 未意识到的

erosion:   
  title: erosion
  text: __erosion__ [ɪ'rəʊʒn] n. 腐蚀；磨损

exclusively:   
  title: exclusively
  text: __exclusively__ [ɪk'skluːsɪvlɪ] ad. 专有地，专门地

feather:   
  title: feather
  text: __feather__ [ˈfeðə(r)] n. 羽毛，翎毛

pronounceable:   
  title: pronounceable
  text: __pronounceable__ [prə'naʊnsəbl] a. （指声音）发得出的；（指词）可发音的

bare:   
  title: bare
  text: __bare__ [beə(r)] a. 赤裸的，光秃的

luggage:   
  title: luggage
  text: __luggage__ [ˈlʌgɪdʒ] n. 行李

hose:   
  title: hose
  text: |
    __hose__ [həuz] n. 软管  

    __hose__ vt. 用软管淋

bulb:   
  title: bulb
  text: __bulb__ [bʌlb] n. 灯泡

internal:   
  title: internal
  text: __internal__ [ɪnˈtɜːnl] a. 内部的，国内的

ion:   
  title: ion
  text: __ion__ [ˈaɪən] n. 离子

cruise:   
  title: cruise
  text: |
    __cruise__ [kruːz] v. 航游，巡航；（出租车、船等）缓慢巡行 

    __cruise__ n. 旅游，游戈

illusion:   
  title: illusion
  text: __illusion__ [ɪˈluːʒn] n. 幻想中的事物，错误的观念；错觉，幻觉，假象

shave:   
  title: shave
  text: __shave__ [ʃeɪv] n./v. 修面