# ==============================================================================
# Word List 14
# ==============================================================================

divide:   
  title: divide
  text: |
    __divide__ [dɪˈvaɪd] v. 分开，分隔；分配，分享；除（以）  

    __divide__ n. 分歧，差异；分界线，分水岭

gross:   
  title: gross
  text: __gross__ [grəus] a. 总的，毛的

cloakroom:   
  title: cloakroom
  text: __cloakroom__ [ˈkləukrum] n. 衣帽间； <英> 洗手间

short-term:   
  title: short-term
  text: __short-term__  [ʃɔ:t tɜ:m] a. 短期的

refusal:   
  title: refusal
  text: __refusal__ [rɪˈfjuːzl] n. 拒绝

coupon:   
  title: coupon
  text: __coupon__ [ˈkuːpɔn] n. 优惠券；票证；配给券；参赛表，订货单

tome:   
  title: tome
  text: __tome__ [təum] n. 册，大部头书；（有学术价值的）巨著

toxin:   
  title: toxin
  text: __toxin__ [ˈtɔksɪn] n. 毒素，毒质

simultaneously:   
  title: simultaneously
  text: __simultaneously__ [ˌsɪməl'teɪnɪəslɪ] ad. 同时地

ridiculous:   
  title: ridiculous
  text: __ridiculous__ [rɪˈdɪkjuləs] a. 荒谬的；可笑的

chip:   
  title: chip
  text: |
    __chip__ [tʃɪp] n. 碎片；芯片；瑕疵  

    __chip__ v. 削（或凿）下（屑片或碎片）

polish:   
  title: polish
  text: |
    __polish__ [ˈpɔlɪʃ] v. 磨光，擦亮；使优美，润饰  

    __polish__ n. 擦光剂，上光蜡

wonder:   
  title: wonder
  text: |
    __wonder__ [ˈwʌndə(r)] v. 诧异，奇怪；纳闷，想知道  

    __wonder__ n. 惊奇，惊异；奇迹，奇事

scholarship:   
  title: scholarship
  text: __scholarship__ [ˈskɔləʃɪp] n. 奖学金；学问，学识

familiarise:   
  title: familiarise
  text: __familiarise__ [fəˈmɪlɪəraɪz] vt. 使熟悉，使通晓；使家喻户晓 to learn about; become acquainted with
  example: it is up to parents to familiarise themselves with the options and monotor their children's viewing choices

expectancy:   
  title: expectancy
  text: __expectancy__ [ɪk'spektənsɪ] n. 期待，期望；预期数额（如寿命等）

shilling:   
  title: shilling
  text: __shilling__ [ˈʃɪlɪŋ] n. 先令

blueprint:   
  title: blueprint
  text: __blueprint__ [ˈbluːprɪnt] n. 蓝图；方案

interplay:   
  title: interplay
  text: __interplay__ [ˈɪntəpleɪ] vi./n. 相互作用，相互影响

convenient:   
  title: convenient
  text: __convenient__ [kənˈviːnɪənt] a. 方便的，便利的；适宜的

genuine:   
  title: genuine
  text: __genuine__ [ˈdʒenjuɪn] a. 真正的；真实的

attentive:   
  title: attentive
  text: __attentive__ [əˈtentɪv] a. 注意的，专心的；关心的，体贴的；留意的

observation:   
  title: observation
  text: __observation__ [ˏɔbzəˈveɪʃn] n. 观察，观测；监视；评述，评论

personal:   
  title: personal
  text: __personal__ [ˈpɜːsənl] a. 个人的，私人的；亲自的，本人的；身体的，人身的

vitality:   
  title: vitality
  text: __vitality__ [vaɪˈtælətɪ] n. 生命力，活力

requirement:   
  title: requirement
  text: __requirement__ [rɪ'kwaɪəmənt] n. 需要，需求，要求；需要的东西；必要条件

advisable:   
  title: advisable
  text: __advisable__ [ədˈvaɪzəbl] n. 可取的，适当的；明智的

bankrupt:   
  title: bankrupt
  text: __bankrupt__ [ˈbæŋkrʌpt] a. 破产的

deplete:   
  title: deplete
  text: __deplete__ [dɪˈpliːt] vt. 倒空；（使）枯竭；消耗

influence:   
  title: influence
  text: |
    __influence__ [ˈɪnfluəns] vt. 影响  

    __influence__ n. 影响力；产生影响力的人

fantasy:   
  title: fantasy
  text: __fantasy__ [ˈfæntəsɪ] n. 想像 the product of a creative imagination
  example: the characters and plot are not real, and the story can be drama, science fiction, or fantasy

tragic:   
  title: tragic
  text: __tragic__ [ˈtrædʒɪk] a. 悲惨的；悲剧（性）的

splint:   
  title: splint
  text: |
    __splint__ [splɪnt] n. 细木梗；[医] （用于固定受伤肢体的）夹板  

    __splint__ vt. 用夹板夹

foam:   
  title: foam
  text: |
    __foam__ [fəum] n. 泡沫；泡沫材料  

    __foam__ vi. 起泡沫

occupation:   
  title: occupation
  text: __occupation__ [ˏɔkjuˈpeɪʃn] n. 占领；职业；消遣

format:   
  title: format
  text: |
    __format__ [ˈfɔːmt] vt. 使格式化  

    __format__ n. 安排，计划；版式；格式

bachelor:   
  title: bachelor
  text: __bachelor__ [ˈbætʃələ(r)] n. 学士；单身汉

typhoon:   
  title: typhoon
  text: __typhoon__ [taɪˈfuːn] n. 台风

appointment:   
  title: appointment
  text: __appointment__ [əˈpɔɪntmənt] n. 约会
  example: she had an appointment to paint her nail

slope:   
  title: slope
  text: |
    __slope__ [sləup] n. 斜坡；倾斜  

    __slope__ vi 倾斜

complex:   
  title: complex
  text: |
    __complex__ [ˈkɔmpleks] n. 综合体，集合体；建筑群；情结  

    __complex__ a. 合成的，综合的；复杂的，难懂的

overhead:   
  title: overhead
  text: |
    __overhead__ [ˈəuvəhed] a. 在头顶上的；高架的  n. 天花板；企业管理费用

    __population__ [ˏpɔpjuˈleɪʃn] n. 人口

prey:   
  title: prey
  text: |
    __prey__ [preɪ] n. 猎物，捕获物；牺牲品，战利品  

    vi. 捕食；折磨，使烦恼；掠夺

catalogue:   
  title: catalogue
  text: |
    __catalogue__ [ˈkætəlɔg] n. 目录；系列  

    __catalogue__ vt. 编目录；记载

prerequisite:   
  title: prerequisite
  text: |
    __prerequisite__ [ˌpri:'rekwəzɪt] n. 先决条件，前提；必备条件  

    __prerequisite__ a. 必备的

assessment:   
  title: assessment
  text: __assessment__ [əˈsesmənt] n. 判定，评定；核定的付款额；看法，评价

suggest:   
  title: suggest
  text: __suggest__ [səˈdʒest] v. 建议，提出；暗示

volt:   
  title: volt
  text: __volt__ [vəult] n. 伏特

weed:   
  title: weed
  text: __weed__ [wiːd] n. 杂草

screw:   
  title: screw
  text: |
    __screw__ [skruː] v. 用螺钉固定  

    __screw__ n. 螺丝（钉）

enlighten:   
  title: enlighten
  text: __enlighten__ [ɪnˈlaɪtn] vt. 启发；开导；阐明

textile:   
  title: textile
  text: __textile__ [ˈtekstaɪl] n. 纺织品

hesitate:   
  title: hesitate
  text: __hesitate__ [ˈhezɪteɪt] vi. 犹豫；不情愿

tutor:   
  title: tutor
  text: |
    __tutor__ [ˈtjuːtə(r)] v. （给……）当家庭教师  

    __tutor__ n. 导师；家庭教师

topsoil:   
  title: topsoil
  text: __topsoil__ [ˈtɒpsɔɪl] n. 表层土

background:   
  title: background
  text: __background__ [ˈbækgraund] n. 背景；经历；后台；不重要或不引人注目的地方

impossible:   
  title: impossible
  text: __impossible__ [ɪmˈpɔsəbl] a. 不可能的，办不到的

surgeon:   
  title: surgeon
  text: __surgeon__ [ˈsɜːdʒən] n. 外科医生

promise:   
  title: promise
  text: __promise__ [ˈprɔmɪs] n./v. 允诺，保证；预兆，预示

battery:   
  title: battery
  text: __battary__ [ˈbætərɪ] n. 电池（组），蓄电池（组）

thunder:   
  title: thunder
  text: |
    __thunder__ [ˈθʌndə(r)] n. 雷；雷声  

    __thunder__ v. 打雷；轰隆响

delicate:   
  title: delicate
  text: __delicate__ [ˈdelɪkət] a. 纤细的；精巧的；微妙的

account:   
  title: account
  text: |
    __account__ [əˈkaunt] v. 说明，解释；（在数量、比例方面）占；导致  

    __account__ n. 账，账户；叙述，说明

booklet:   
  title: booklet
  text: __booklet__ [ˈbuklɪt] n. 小册子

layout:   
  title: layout
  text: __layout__ [ˈleɪaʊt] n. 布局，安排，设计

venture:   
  title: venture
  text: |
    __venture__ [ˈventʃə(r)] v. 敢于去；拿……冒险，冒……的险  

    __venture__ n. 风险投资，（商业等的）风险项目

shrink:   
  title: shrink
  text: __shrink__ [ʃrɪŋk] v. （使）收缩；萎缩 to make or become smaller
  example: since the 1960s, the Aral Sea in Central Asia has shrunk to less than 10 percent of its original size, which has led to many negative consequence

gland:   
  title: gland
  text: __gland__ [glænd] n. 腺

curriculum:   
  title: curriculum
  text: __curriculum__ [kəˈrɪkjuləm] n. 课程，（学校等的）全部课程

shortage:   
  title: shortage
  text: __shotage__ [ˈʃɔːtɪdʒ] n. 不足，缺少

accreditation:   
  title: accreditation
  text: __accreditation__ [əˌkredɪˈteɪʃn] n. 证明合格，鉴定合格

clerk:   
  title: clerk
  text: __clerk__ [klɑːk] n. 办事员；职员
